name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 3.2.0)'
        required: true
        type: string
      distribution-channel:
        description: 'Distribution channel (stable, beta, alpha)'
        required: true
        type: string
        default: 'stable'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Update version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Update CHANGELOG
        run: |
          DATE=$(date +"%Y-%m-%d")
          sed -i "s/## \[Unreleased\]/## \[Unreleased\]\n\n## \[${{ github.event.inputs.version }}\] - $DATE/" CHANGELOG.md
      
      - name: Commit changes
        run: |
          git add package.json CHANGELOG.md
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}"
          git push origin main
          git push origin "v${{ github.event.inputs.version }}"
  
  trigger-build:
    needs: prepare-release
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: ${{ github.event.inputs.distribution-channel }}